/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DogsDogIdExercisesRouteImport } from './routes/dogs.$dogId.exercises'
import { Route as DogsDogIdEditRouteImport } from './routes/dogs.$dogId.edit'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsDogIdExercisesRoute = DogsDogIdExercisesRouteImport.update({
  id: '/dogs/$dogId/exercises',
  path: '/dogs/$dogId/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const DogsDogIdEditRoute = DogsDogIdEditRouteImport.update({
  id: '/dogs/$dogId/edit',
  path: '/dogs/$dogId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/profile': typeof ProfileRoute
  '/workspace': typeof WorkspaceRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId/exercises': typeof DogsDogIdExercisesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/profile': typeof ProfileRoute
  '/workspace': typeof WorkspaceRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId/exercises': typeof DogsDogIdExercisesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/goals': typeof GoalsRoute
  '/learn': typeof LearnRoute
  '/profile': typeof ProfileRoute
  '/workspace': typeof WorkspaceRoute
  '/dogs/$dogId/edit': typeof DogsDogIdEditRoute
  '/dogs/$dogId/exercises': typeof DogsDogIdExercisesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/goals'
    | '/learn'
    | '/profile'
    | '/workspace'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId/exercises'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/goals'
    | '/learn'
    | '/profile'
    | '/workspace'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId/exercises'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/goals'
    | '/learn'
    | '/profile'
    | '/workspace'
    | '/dogs/$dogId/edit'
    | '/dogs/$dogId/exercises'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  GoalsRoute: typeof GoalsRoute
  LearnRoute: typeof LearnRoute
  ProfileRoute: typeof ProfileRoute
  WorkspaceRoute: typeof WorkspaceRoute
  DogsDogIdEditRoute: typeof DogsDogIdEditRoute
  DogsDogIdExercisesRoute: typeof DogsDogIdExercisesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/$dogId/exercises': {
      id: '/dogs/$dogId/exercises'
      path: '/dogs/$dogId/exercises'
      fullPath: '/dogs/$dogId/exercises'
      preLoaderRoute: typeof DogsDogIdExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogs/$dogId/edit': {
      id: '/dogs/$dogId/edit'
      path: '/dogs/$dogId/edit'
      fullPath: '/dogs/$dogId/edit'
      preLoaderRoute: typeof DogsDogIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  GoalsRoute: GoalsRoute,
  LearnRoute: LearnRoute,
  ProfileRoute: ProfileRoute,
  WorkspaceRoute: WorkspaceRoute,
  DogsDogIdEditRoute: DogsDogIdEditRoute,
  DogsDogIdExercisesRoute: DogsDogIdExercisesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
